services:
  - type: web
    name: stocks-analyzer
    env: docker
    repo: https://github.com/omerwer/Personal-projects
    branch: main
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    buildFilter:
      paths:
        - python/stocks_analysis/web_service/**
